name: Sync Artists Every 5 Hours

on:
  schedule:
    - cron: "0 */5 * * *" # Every 5 hours UTC
  workflow_dispatch: # Allows manual run

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run the sync script
        run: node runSync.js
        env:
          FIREBASE_ADMIN_KEY: ${{ secrets.FIREBASE_ADMIN_KEY }}
